// src/lib/theme/stylePresets.ts
// Home style preset metadata (single source of truth)

import type { FxMode } from '@/types/uiMode'

export type StylePresetId = FxMode
export type StyleCategory = 'classic' | 'ambient' | 'creative' | 'entertainment' | 'tech'

export interface StylePreset {
  id: FxMode
  labelZh: string
  labelEn: string
  tagline: string
  category: StyleCategory
  hasVideo: boolean
  hasBgm: boolean
  hasGpuLayer: boolean
  previewType: 'gradient' | 'neon' | 'rgb-flow' | 'anime' | 'stream' | 'solid'
  accentColor: string
  secondaryColor: string
  darkAccentColor: string
  darkSecondaryColor: string
}

export const STYLE_PRESETS: Record<FxMode, StylePreset> = {
  default: {
    id: 'default',
    labelZh: '常态',
    labelEn: 'Default',
    tagline: '纯净留白，回归阅读本质',
    category: 'classic',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'solid',
    accentColor: '#5d88a7',
    secondaryColor: '#c8d8e4',
    darkAccentColor: '#8baec8',
    darkSecondaryColor: '#2a3a4a',
  },
  glass: {
    id: 'glass',
    labelZh: '晶透',
    labelEn: 'Glass',
    tagline: '磨砂玻璃，通透层次感',
    category: 'ambient',
    hasVideo: true,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'gradient',
    accentColor: '#8bb8d4',
    secondaryColor: '#d8e8f0',
    darkAccentColor: '#6a9ab8',
    darkSecondaryColor: '#1a2a38',
  },
  liquid: {
    id: 'liquid',
    labelZh: '液态',
    labelEn: 'Liquid',
    tagline: '流动背景与背景音乐，沉浸氛围',
    category: 'ambient',
    hasVideo: true,
    hasBgm: true,
    hasGpuLayer: true,
    previewType: 'gradient',
    accentColor: '#6fa4ce',
    secondaryColor: '#c0ddf0',
    darkAccentColor: '#5a8ab0',
    darkSecondaryColor: '#1a2a3a',
  },
  cyberpunk: {
    id: 'cyberpunk',
    labelZh: '赛博朋克',
    labelEn: 'Cyberpunk',
    tagline: '霓虹暗夜，高对比科技感',
    category: 'creative',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'neon',
    accentColor: '#ff2d78',
    secondaryColor: '#00f0ff',
    darkAccentColor: '#ff2d78',
    darkSecondaryColor: '#00f0ff',
  },
  rgb: {
    id: 'rgb',
    labelZh: 'RGB',
    labelEn: 'RGB Flow',
    tagline: '流光渐变边框，点亮视觉焦点',
    category: 'creative',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'rgb-flow',
    accentColor: '#a855f7',
    secondaryColor: '#06b6d4',
    darkAccentColor: '#c084fc',
    darkSecondaryColor: '#22d3ee',
  },
  anime: {
    id: 'anime',
    labelZh: '动漫',
    labelEn: 'Anime',
    tagline: '干净明亮，日系插画感',
    category: 'entertainment',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'anime',
    accentColor: '#f472b6',
    secondaryColor: '#a78bfa',
    darkAccentColor: '#f0abfc',
    darkSecondaryColor: '#c4b5fd',
  },
  stream: {
    id: 'stream',
    labelZh: '流媒体',
    labelEn: 'Stream',
    tagline: '层次卡片，横向内容节奏',
    category: 'entertainment',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'stream',
    accentColor: '#f97316',
    secondaryColor: '#facc15',
    darkAccentColor: '#fb923c',
    darkSecondaryColor: '#fde047',
  },
  aurora: {
    id: 'aurora',
    labelZh: '极光',
    labelEn: 'Aurora',
    tagline: '冷光浮动，山海空气感',
    category: 'ambient',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'gradient',
    accentColor: '#58d8cc',
    secondaryColor: '#7f8dff',
    darkAccentColor: '#6ee5da',
    darkSecondaryColor: '#9da7ff',
  },
  graphite: {
    id: 'graphite',
    labelZh: '石墨',
    labelEn: 'Graphite',
    tagline: '低饱和工程感，冷静清晰',
    category: 'classic',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'solid',
    accentColor: '#9da9b8',
    secondaryColor: '#677283',
    darkAccentColor: '#b4c0d0',
    darkSecondaryColor: '#7f8c9f',
  },
  sakura: {
    id: 'sakura',
    labelZh: '樱雾',
    labelEn: 'Sakura Mist',
    tagline: '柔软粉紫，轻甜玻璃层次',
    category: 'entertainment',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'anime',
    accentColor: '#f08bc2',
    secondaryColor: '#c9a7ff',
    darkAccentColor: '#f3a7d2',
    darkSecondaryColor: '#d6beff',
  },
  ocean: {
    id: 'ocean',
    labelZh: '深海',
    labelEn: 'Ocean Depth',
    tagline: '深蓝冷光，稳定技术氛围',
    category: 'ambient',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'stream',
    accentColor: '#4fb0df',
    secondaryColor: '#2cd4c7',
    darkAccentColor: '#70c4ed',
    darkSecondaryColor: '#50ddd2',
  },
  ember: {
    id: 'ember',
    labelZh: '余烬',
    labelEn: 'Ember',
    tagline: '暖黑对比，电影级光影质感',
    category: 'creative',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'neon',
    accentColor: '#ff8b4a',
    secondaryColor: '#ffd26a',
    darkAccentColor: '#ffa66f',
    darkSecondaryColor: '#ffe08f',
  },
  haru: {
    id: 'haru',
    labelZh: '春日',
    labelEn: 'Haru Breeze',
    tagline: '清新日系，温柔校园轻小说感',
    category: 'entertainment',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'anime',
    accentColor: '#87CEEB',
    secondaryColor: '#FFB7C5',
    darkAccentColor: '#6DA9C8',
    darkSecondaryColor: '#E6A3B1',
  },
  mugen: {
    id: 'mugen',
    labelZh: '梦境',
    labelEn: 'Mugen Glass',
    tagline: '梦幻玻璃，二次元星光虚拟感',
    category: 'ambient',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'neon',
    accentColor: '#B088FF',
    secondaryColor: '#78D6FF',
    darkAccentColor: '#9673D6',
    darkSecondaryColor: '#66B5D9',
  },
  'cyber-hacker': {
    id: 'cyber-hacker',
    labelZh: '终端',
    labelEn: 'Hacker Terminal',
    tagline: '黑客终端赛博朋克，数据流与命令面板',
    category: 'tech',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'neon',
    accentColor: '#00FF41',
    secondaryColor: '#008F11',
    darkAccentColor: '#00FF41',
    darkSecondaryColor: '#003B00',
  },
  'cyber-corp': {
    id: 'cyber-corp',
    labelZh: '财阀',
    labelEn: 'Corporate Tech',
    tagline: '企业科技赛博朋克，未来总部控制中心',
    category: 'tech',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'neon',
    accentColor: '#08F7FE',
    secondaryColor: '#09FBD3',
    darkAccentColor: '#08F7FE',
    darkSecondaryColor: '#00A4CC',
  },
  'cyber-game': {
    id: 'cyber-game',
    labelZh: '枢纽',
    labelEn: 'Game Concept',
    tagline: '游戏概念赛博朋克，高视觉冲击世界观',
    category: 'creative',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'neon',
    accentColor: '#FF0055',
    secondaryColor: '#FF003C',
    darkAccentColor: '#FF0055',
    darkSecondaryColor: '#7A0026',
  },
  'future-tech': {
    id: 'future-tech',
    labelZh: '未来科工',
    labelEn: 'Quantum Core',
    tagline: '高级未来科技感，量子全息数据与空间阵列',
    category: 'tech',
    hasVideo: false,
    hasBgm: false,
    hasGpuLayer: false,
    previewType: 'stream',
    accentColor: '#00D8FF',
    secondaryColor: '#0055FF',
    darkAccentColor: '#00D8FF',
    darkSecondaryColor: '#002B80',
  },
}

export const ALL_STYLE_IDS: FxMode[] = [
  'default',
  'liquid',
  'glass',
  'cyberpunk',
  'cyber-hacker',
  'cyber-corp',
  'cyber-game',
  'future-tech',
  'rgb',
  'anime',
  'haru',
  'mugen',
  'stream',
  'aurora',
  'graphite',
  'sakura',
  'ocean',
  'ember',
]

export const FX_CLASSES: Record<FxMode, string> = {
  default: 'home-default-mode',
  glass: 'home-glass-mode',
  liquid: 'home-liquid-mode',
  cyberpunk: 'home-cyberpunk-mode',
  'cyber-hacker': 'home-cyber-hacker-mode',
  'cyber-corp': 'home-cyber-corp-mode',
  'cyber-game': 'home-cyber-game-mode',
  'future-tech': 'home-future-tech-mode',
  rgb: 'home-rgb-mode',
  anime: 'home-anime-mode',
  haru: 'home-haru-mode',
  mugen: 'home-mugen-mode',
  stream: 'home-stream-mode',
  aurora: 'home-aurora-mode',
  graphite: 'home-graphite-mode',
  sakura: 'home-sakura-mode',
  ocean: 'home-ocean-mode',
  ember: 'home-ember-mode',
}

export function needsGpuLayer(mode: FxMode): boolean {
  return mode === 'liquid'
}
