// scripts/check-static-params-count.ts
// Counts params generated by scanStaticPaths
import fs from 'fs'
import path from 'path'

const CONTENT_DIR = path.join(process.cwd(), 'src', 'content')

function addParamVariantsOriginal(set: Set<string>, slug: string) {
  const parts = slug.split('/').filter(Boolean)
  if (!parts.length) return
  set.add(parts.join('/'))
  set.add(parts.map((seg) => encodeURIComponent(seg)).join('/'))
}

function addParamVariantsEncodedOnly(set: Set<string>, slug: string) {
  const parts = slug.split('/').filter(Boolean)
  if (!parts.length) return
  // Only add encoded version - the canonical format
  set.add(parts.map((seg) => encodeURIComponent(seg)).join('/'))
}

function scanStaticPaths(
  dir: string,
  baseSlug: string,
  paramsSet: Set<string>,
  variantFn: (set: Set<string>, slug: string) => void
): boolean {
  if (!fs.existsSync(dir)) return false
  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => !entry.name.startsWith('_') && !entry.name.startsWith('.'))

  let hasDoc = false

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const nextSlug = baseSlug ? `${baseSlug}/${entry.name}` : entry.name
      const childHasDoc = scanStaticPaths(path.join(dir, entry.name), nextSlug, paramsSet, variantFn)
      if (childHasDoc) {
        variantFn(paramsSet, nextSlug)
        hasDoc = true
      }
      continue
    }

    if (!/\.mdx?$/.test(entry.name)) continue
    const fileSlug = entry.name.replace(/\.mdx?$/, '')
    const slug = baseSlug ? `${baseSlug}/${fileSlug}` : fileSlug
    variantFn(paramsSet, slug)
    hasDoc = true
  }

  return hasDoc
}

function main() {
  console.log('\n=== Static Params Count Comparison ===\n')

  const paramsOriginal = new Set<string>()
  scanStaticPaths(CONTENT_DIR, '', paramsOriginal, addParamVariantsOriginal)

  const paramsEncoded = new Set<string>()
  scanStaticPaths(CONTENT_DIR, '', paramsEncoded, addParamVariantsEncodedOnly)

  console.log('--- Original (addParamVariants) ---')
  console.log(`Total params: ${paramsOriginal.size}`)
  console.log(`Sample (first 5): ${Array.from(paramsOriginal).slice(0, 5).join(', ')}`)
  console.log('')

  console.log('--- Encoded Only ---')
  console.log(`Total params: ${paramsEncoded.size}`)
  console.log(`Sample (first 5): ${Array.from(paramsEncoded).slice(0, 5).join(', ')}`)
  console.log('')

  console.log('--- Comparison ---')
  console.log(`Reduction: ${paramsOriginal.size - paramsEncoded.size} params (${Math.round((1 - paramsEncoded.size / paramsOriginal.size) * 100)}%)`)
  console.log('')
}

main()
