name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack
        run: git archive --format=tar.gz -o release.tar.gz HEAD


      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "release.tar.gz"
          target: "/root"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /root/Wexler-s-Notes
            tar -xzf /root/release.tar.gz -C /root/Wexler-s-Notes
            cd /root/Wexler-s-Notes
            docker build -t wexler-notes-image .
            docker rm -f my-nginx || true
            docker run -d --name my-nginx --restart unless-stopped -p 80:80 wexler-notes-image
